### ISSUE TITLE
Allow system properties to be specified in the manifest

### ISSUE THREAD

**Issue by rmuchall** [puniverse/capsule-daemon#8]
Hi circlespainter,

I'd like to suggest a feature/improvement:
It would be useful to be able to specify system properties in the jar manifest and have capsule-daemon utilize these as defaults if no system properties are specified in the command line.
e.g.

```
    capsuleManifest {
        caplets << "DaemonCapsule"
        // Linux
        systemProperties["capsule.daemon.debug"] = "true"
        systemProperties["capsule.daemon.verbose"] = "true"
        // System
        systemProperties["capsule.log"] = "verbose"
        systemProperties["capsule.daemon.stdoutFile"] = "/home/mudserver/logs/out.log"
        systemProperties["capsule.daemon.stderrFile"] = "/home/mudserver/logs/err.log"
    }
```

Thanks! :)

**Comment by pron** [comment]
System properties can be set in the manifest, but not those that begin with `capsule`. [This is intentional](https://github.com/puniverse/capsule/issues/99). Capsules need to be portable, and we don't want the manifest setting values that may fail on different machines (like absolute file paths).

We can consider adding manifest attributes on a case-by-case basis. For example, the default for the `capsule.log` property can be set with the `Capsule-Log-Level` attribute.

However, the behavior you want can already be achieved by writing your own caplet and listing it in addition to the daemon caplet.

**Comment by circlespainter** [comment]
Also, `capsule-daemon` (and other caplets as well) should already support equivalent manifest entries for settings that make sense to ship with the capsule itself because they are app- or capsule-/caplet- related (as opposed to execution environment-related) or can act as convenient and meaningful defaults.

For example there are already `Daemon-Stdout-File` and `Daemon-Stderr-File`. Instead capsule/caplet meta-settings (like `log` or `daemon.debug`) don't make sense to be hard-coded in a capsule because they relate to single executions and should instead always be specified at launch time.

**Comment by rmuchall** [comment]
Ah I understand the design, that makes perfect sense.
Many thanks for your response and information :)
